### ISSUE TITLE
In RNV modes the DME should display distance to waypoint, not to VOR 

### ISSUE THREAD

**Issue by bitwisetech** [reiszner/KNS80#1]
Hi !  
 mentioned on the forum: 
[Here](https://forum.flightgear.org/viewtopic.php?f=4&t=41836)

-  to fix: in kns80.nas @ 15: 
- 
#var dme_distance      = props.globals.getNode(config.getValue("params/dme-indicated-distance-nm"),0);
var dme_distance      = props.globals.getNode("instrumentation/kns80/nav/nav-distance-nm",0);

  Thanks !

**Comment by reiszner** [comment]
Thats a quick fix, but lead to another problem (see Issue #2).
But its fixed now.

thx for poiting it out.
