### ISSUE TITLE
KNS80 DME Speed and distance display flicker no values / bad values

### ISSUE THREAD

**Issue by bitwisetech** [reiszner/KNS80#2]
Hi ! 
  In kns80.nas @ 17 setlistener(dme_distance, func(dist) {
if the debug print statement is enables the DME display is steady and correct, without the console print the DME display is not stable; it looks as if the time delta
becomes zero sometimes when the listener is fired. 

 To fix: 
 `setlistener(dme_distance, func(dist) {
    if (dist.getValue() > 0.0) {
        var dme_dist      = dist.getValue();
        var dme_dist_last = getprop("instrumentation/kns80/dme/last-distance-nm") or 0;
        var dme_time      = getprop("sim/time/elapsed-sec") or 0;
        var dme_time_last = getprop("instrumentation/kns80/dme/last-time") or 0;
        var dT =  (dme_time - dme_time_last);
        if ( dT > 0.99 ) {
            # printf("D: %.3f  pD: %.3f  dD: %.3f   Tc: %.3f  pT: %.3f dT: %.3f", dme_dist, \
            #  dme_dist_last, (dme_dist - dme_dist_last), dD, dme_time, dme_time_last, dT);
            var factor        = abs(dme_dist - dme_dist_last) / dT;
            var speed         = factor * 3600;
            var minute        = dme_dist / (factor * 60);
            if (speed <   0.0) speed = 0.0;
            if (speed > 999.0) speed = 999.0;
            if (minute <  0.0) minute = 0.0;
            if (minute > 99.0) minute = 99.0;
            setprop("instrumentation/kns80/dme/indicated-distance-nm", dme_dist);
            setprop("instrumentation/kns80/dme/indicated-ground-speed-kt", speed);
            setprop("instrumentation/kns80/dme/indicated-time-min", minute);
            setprop("instrumentation/kns80/dme/last-distance-nm", dme_dist);
            setprop("instrumentation/kns80/dme/last-time", dme_time);
        }    
    }
},0,0);

`

**Comment by bitwisetech** [comment]
(Edit) Apologies if this is an invalid issue, I'm having difficulties understanding which is 'source' and which is 'sink' in order to configure the connections and config files for KAP140, KNS80 and KCS55 on the Lancair.

**Comment by reiszner** [comment]
Your fix for Issue #1 set a trigger loop.
I have now moved some calculations from propfilter to nasal for a better handling.
It should now work as expected.

Please check

PS: do you have a repo for the Lancair so that i can investigate and help?
