### ISSUE TITLE
Inner knob position randomly advances

### ISSUE THREAD

**Issue by bitwisetech** [reiszner/KNS80#3]
Hi, 
 Here on the Lancair235, the fracional part of the frequency advances without the knob being touched.  I put debug prints into kns80.nas kns80_inner listener and confirm the listener is firing with an arg of 1.  Altough in the property browser the knob-inner event shows no cahange
from zero, setting that prop to zero stops the listener from firing.
  I added two lines to Systems/initialistation.xml to set both inner and out knob variables to zero and the issue is fixed: 

`--- /data/Lancair-235-git/Systems/initialisation.xml	2024-02-26 12:38:04.259033372 -0500
+++ /comm/fgfs/fgaddon/Aircraft/Lancair-235/Systems/initialisation.xml	2024-03-22 12:54:16.118197431 -0400
@@ -128,6 +128,8 @@
     <data-mode                        type="int">0</data-mode>
     <dme-hold                         type="bool">false</dme-hold>
     <use                              type="int">0</use>
+    <kns80_inner                      type="int">0</kns80_inner>
+    <kns80_outer                      type="int">0</kns80_outer>
     <display                          type="int">0</display>
     <display-timer                    type="double">0.0</display-timer>
     <displayed-frequency              type="double">0.0</displayed-frequency>
`
I don't know the cause, uninitialised property ?? but the above fixes for me. 
I thought I'd passed a link to the Lancair updates on the forum but, anyway: 

[https://github.com/bitwisetech/Lancair-235](url)

**Comment by reiszner** [comment]
Hi bitwisetech,

The `kns80_inner` and `kns80_outer` are variables only existing in nasal space.
Its curios if that changes fix your problems.

I have now investigated your problem and found a mistake in your aircraft files.
Inside the *-set.xml file, there is a part
```
<sim>
    …
    <instrumentation>
        …
    </instrumentation>
    …
</sim>
```
but also a part
```
<instrumentation>
    …
</instrumentation>
```
outside of the <sim> block.
Thats two differend things.
The first instrumentation definition inside the sim-block, request the simulation of instruments that FGFS serves.
The second instrumentation definition outside the sim-block, are only property definitions and initialisation.
In your case, this declarations are in `Systems/lancair235-base.xml` and should be

```
<sim>
    …
    <instrumentation include="instrumentation.xml" />
    …
</sim>

<instrumentation include="initialisation.xml" />
```

I will set a pull request on the Lancair-235 with all changes.
